version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./bot/:/app/bot/
      - ./main.js:/app/main.js
      - ./node_modules/:/app/node_modules/
    restart: always

  db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./mnt/mongo_data:/data/db
