version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules/

volumes:
  node_modules:
